artifact_uri: file:///C:/Users/Lenovo/Desktop/yolo-gun-detection/Weapons-and-Knives-Detector-with-YOLOv8/runs/mlflow/347070787115567756/9f3b300cc75149fbab4aaf1c399aa953/artifacts
end_time: 1748887224569
entry_point_name: ''
experiment_id: '347070787115567756'
lifecycle_stage: active
run_id: 9f3b300cc75149fbab4aaf1c399aa953
run_name: ak47_detection5
run_uuid: 9f3b300cc75149fbab4aaf1c399aa953
source_name: ''
source_type: 4
source_version: ''
start_time: 1748884640585
status: 3
tags: []
user_id: Lenovo
