artifact_location: file:///C:/Users/Lenovo/Desktop/yolo-gun-detection/Weapons-and-Knives-Detector-with-YOLOv8/runs/mlflow/347070787115567756
creation_time: 1748884640298
experiment_id: '347070787115567756'
last_update_time: 1748884640298
lifecycle_stage: active
name: /Shared/Ultralytics
