artifact_location: file:///C:/Users/Lenovo/Desktop/yolo-gun-detection/Weapons-and-Knives-Detector-with-YOLOv8/runs/mlflow/0
creation_time: 1748884640274
experiment_id: '0'
last_update_time: 1748884640274
lifecycle_stage: active
name: Default
